### ISSUE TITLE
Using Free in multiple files

### ISSUE THREAD

**Issue by jesuspc** [gcanti/fp-ts-contrib#28]
**Do you want to request a _feature_ or report a _bug_?**

I'm not sure whether it qualifies as a bug, it may be my lack of understanding.

**What is the current behaviour?**

Reviewing the example code at the test directory of this project I have attempted to use Free. According to the test code the file where the monad Expr is defined needs to contain the following bit of code (or so it seems):

```
type ExprF<A> = Add<A> | Lit<A>

declare module 'fp-ts/lib/HKT' {
  interface URItoKind<A> {
    Expr: ExprF<A>
  }
}
```

Without it, the compiler displays an error `No overload matches this call`. This works well when only one file in the project defines an ExprF but when there is more than one occurrence they step on each other.  So, for instance having two files on the same project:

```
// addLit.ts
type ExprF<A> = Add<A> | Lit<A>

declare module 'fp-ts/lib/HKT' {
  interface URItoKind<A> {
    Expr: ExprF<A>
  }
}
```

and

```
// fooBar.ts
type ExprF<A> = Foo<A> | Bar<A>

declare module 'fp-ts/lib/HKT' {
  interface URItoKind<A> {
    Expr: ExprF<A>
  }
}
```

I get an error `Subsequent property declarations must have the same type. Property 'Expr' must be of type 'Expr<A>', but here has type 'Exp<A>'`

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**

Create a different Free Expr on two files in the same package as described above.

**What is the expected behavior?**

Be able to have different Expr in the same project.

**Which versions of fp-ts-contrib, and which browser and OS are affected by this issue? Did this work in previous versions of fp-ts-contrib?**

0.1.6 ~ NixOs 19.09 ~ I don't know

**Comment by gcanti** [comment]
The `URItoKind` interface is a global type-level dictionary, its keys must be unique

```ts
declare module 'fp-ts/lib/HKT' {
  interface URItoKind<A> {
//  v-- must be unique
    Expr: ExprF<A>
  }
}
```

**Comment by jesuspc** [comment]
Thanks, I managed to make it work.

I am now considering to use this implementation of free monads for an application I'm working on. Is it safe to use or are there considerations about stack size/runtime to be had?

**Comment by YBogomolov** [comment]
@jesuspc Please see this episode of Monadic Mondays, where I talked about Free monads and trampolining to ensure stack-safety: https://twitter.com/YuriyBogomolov/status/1130415558556565504
In general, when interpreting Free you're every time reconstructing tree-like class structure. In JS it's not possible to do without some runtime overhead.

**Comment by jesuspc** [comment]
@YBogomolov  Thanks!
