### ISSUE TITLE
Feature request: Do#letL

### ISSUE THREAD

**Issue by kgtkr** [gcanti/fp-ts-contrib#35]
## 🚀 Feature request
I want to declare a variable in Do

### Desired Behavior
`.bindL("a", s => m.of(x))`

### Suggested Solution
`.letL("a", s => x)`

**Comment by gcanti** [comment]
@pfgray WDYT?

**Comment by pfgray** [comment]
Yeah, I think this is reasonable, and have wanted this myself a few times
