### ISSUE TITLE
Pattern Matching

### ISSUE THREAD

**Issue by filonik** [gcanti/fp-ts-contrib#63]
## 🚀 Feature request

Would something like this be useful?

### Current Behavior

Pattern matching is done using if/switch statements in conjunction with type guards.

### Desired Behavior

It would be nice to have a more functional/concise syntax that still provides type safety and exhaustiveness checking (of course).

The following solution was inspired by Peter Fillo's [“Pattern matching” with Typescript done right](https://medium.com/@fillopeter/pattern-matching-with-typescript-done-right-94049ddd671c).

If there is interest, I can create a pull request.

### Suggested Solution

```typescript
export const Tag = '_tag' as const

interface TaggedType {
  [Tag]: string | number | symbol
}

type TypeMap<T extends TaggedType> = {
  [K in T[typeof Tag]]: T extends { [Tag]: K } ? T : never
}

type PatternMap<M, T> = {
  [K in keyof M]: (e: M[K]) => T
}

export type Pattern<T extends TaggedType, U> = PatternMap<TypeMap<T>, U>

export function match<T extends TaggedType, U>(p: Pattern<T, U>): (e: T) => U {
  return (v) => p[v[Tag]](v)
}
```

It can be used as follows:

```typescript
import * as E from 'fp-ts/lib/Either'

export const f = match<E.Either<boolean, number>, string>({
  Left: (e) => `L: ${e.left}`,
  Right: (e) => `R: ${e.right}`,
})

console.log(f(E.right(42))) // "R: 42"
```

The benefits become more obvious if there are more cases, the above is just for illustration.

### Who does this impact? Who is this for?

All users?

### Describe alternatives you've considered

Just using if/switch statements in conjunction with type guards.

### Your environment

| Software      | Version(s) |
| ------------- | ---------- |
| fp-ts         |   2.6.2        |
| fp-ts-contrib |   n/a         |
| TypeScript    |  3.9.2          |

**Comment by filonik** [comment]
I noticed there's already a dedicated library doing something very similar, so maybe it's not needed:

https://github.com/babakness/exhaustive-type-checking

Not sure...

**Comment by gcanti** [comment]
Also [ts-adt](https://github.com/pfgray/ts-adt)

**Comment by steida** [comment]
Why this is helpful? Isn't absurd helper good enough to cover all cases?

**Comment by filonik** [comment]
Consider a simple lambda calculus example.

Here is the conventional approach:

```typescript
function prettyPrintAlg(e: ExprF<string>): string {
  switch (e._tag) {
    case ExpressionTag.Lit:
      return `${e.value}`
    case ExpressionTag.Var:
      return `#${e.index}`
    case ExpressionTag.Lam:
      return `λ(${printParam(e.param)}). ${e.body}`
    case ExpressionTag.App:
      return `${e.fun} (${e.arg})`
    case ExpressionTag.LamN:
      return `λ(${e.params.map(printParam).join(', ')}). ${e.body}`
    case ExpressionTag.AppN:
      return `${e.fun} (${e.args.join(', ')})`
    default:
      absurd(e)
  }
}

export const prettyPrint = cataExpr(prettyPrintAlg))
```

And here is the "pattern matching" approach:

```typescript
const prettyPrinter: Pattern<ExprF<string>, string> = {
  [ExpressionTag.Lit]: (e) => `${e.value}`,
  [ExpressionTag.Var]: (e) => `#${e.index}`,
  [ExpressionTag.Lam]: (e) => `λ(${printParam(e.param)}). ${e.body}`,
  [ExpressionTag.App]: (e) => `${e.fun} (${e.arg})`,
  [ExpressionTag.LamN]: (e) => `λ(${e.params.map(printParam).join(', ')}). ${e.body}`,
  [ExpressionTag.AppN]: (e) => `${e.fun} (${e.args.join(', ')})`,
}

const prettyPrintAlg = match(prettyPrinter)
const prettyPrint = cataExpr(prettyPrintAlg)
```

Two immediate differences are:

1. The second approach is more concise (this essentially comes down to aesthetic preference).
2. The second approach has an explicit "pretty printer" object, which we can manipulate (e.g. we can create a "derived" pretty printer that inherits all cases and overwrites individual ones). 

Those are essentially the main differences that I can think of. Whether they warrant inclusion into the library is another question.

**Comment by steida** [comment]
@filonik Thank you. I think I will stay with pure TS with absurd. It's less magic for me.

**Comment by damoco** [comment]
How ts-adt match an option array? I found a lib for this: https://dev.to/gvergnaud/bringing-pattern-matching-to-typescript-introducing-ts-pattern-v3-0-o1k?signin=true

Don't know if it is the best way so far...

**Comment by danielo515** [comment]
> Also [ts-adt](https://github.com/pfgray/ts-adt)

Is advised to use `ts-adt` ? Or is it better to start using the new helper libaries from effect-ts?
