### ISSUE TITLE
`Zipper` should have `toReadonlyArray`

### ISSUE THREAD

**Issue by SRachamim** [gcanti/fp-ts-contrib#75]
## 🚀 Feature request

As any other data-structure in the _fp-ts_ library, I expect `Zipper` to support `ReadonlyArray`. This is important because most people that use `Zipper` will want to work with immutable data-structures.

### Current Behavior

`Zipper` has `toArray`. Doesn't have `toReadonlyArray`.

### Desired Behavior

`Zipper` should have a `toReadonlyArray` of type: `<A>(z: Zipper<A>) => ReadonlyArray<A>`.

### Suggested Solution

Just alias the new function to `toArray`.

```typescript
export const toReadonlyArray: <A>(fa: Zipper<A>) => ReadonlyArray<A> = toArray
```

PR #76  does exactly that.

### Who does this impact? Who is this for?

It's not a breaking change, so it shouldn't impact anyone. It's for people who cares about immutability.

### Describe alternatives you've considered

The alternative is to use `fromArray` from `fp-ts/ReadonlyArray` after each `toArray` from `fp-ts-contrib/Zipper`:

```typescript
import * as A from 'fp-ts/ReadonlyArray'
import * as Z from 'fp-ts-contrib/Zipper'

const as = pipe(
 Z.of('a'),
 Z.toArray,
 A.fromArray,
)
```

This is what I currently do, but it's not nice and not clean.

### Additional context

Generally I think it's better to have the implementation of `Zipper` uses `ReadonlyArray`.

### Your environment

| Software      | Version(s) |
| ------------- | ---------- |
| fp-ts         |       2.10.4     |
| fp-ts-contrib |      0.1.21      |
| TypeScript    |      4.2      |

**Comment by DenisFrezzato** [comment]
@SRachamim after this https://github.com/gcanti/fp-ts-contrib/pull/76 was merged, can this be closed?

**Comment by SRachamim** [comment]
> @SRachamim after this #76 was merged, can this be closed?

Yes. Thanks.
